### ISSUE TITLE
Cannot capture error automatically

### ISSUE THREAD

**Issue by ardyfeb** [ntegral/nestjs-sentry#1]
When error appear, the error cannot capture automatically to sentry, but work when calling `SentryService`

**Comment by webberig** [comment]
I suspect that the default unhandled exception handling isn't working since NestJS actually handles all exceptions by default ?

This is my solution:

Create an [Interceptor](https://docs.nestjs.com/interceptors):
```
@Injectable()
export class SentryReportingInterceptor implements NestInterceptor {
    intercept(context: ExecutionContext, call$) {
        return call$
            .pipe(catchError(error => {
                withScope(scope => {
                    scope.addEventProcessor(event => parseRequest(event, context.switchToHttp().getRequest()));
                    captureException(error);
                });
                throw error;
            }));
    }
}
```

And configure it globally in your appModule:
```
    providers: [
        {
            provide: APP_INTERCEPTOR,
            useClass: SentryReportingInterceptor,
        }
    ],
```

I think this library could use a construction like this to properly setup the request scope and handle NestJS exceptions.

**Comment by ntegral** [comment]
The SentryService extends the nestjs/logger.  The configurations on the NestJs documentation site are implemented.  Please refer to https://docs.nestjs.com/techniques/logger to see the different configuration options.

**Comment by ntegral** [comment]
Did you accomplish what you were looking to do?

**Comment by cesar3030** [comment]
@ntegral Hi, I referred to the link you posted but I still have issue to have it working.
here is my config:

main.ts:
```typescript
import { SentryService } from '@ntegral/nestjs-sentry';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useLogger(app.get(SentryService));  
  await app.listen(configService.get('PORT'));
}
```
app.module.ts:

```typescript
import { Module } from '@nestjs/common';
import { SentryModule } from '@ntegral/nestjs-sentry';
import { LogLevel } from '@sentry/types';
...

@Module({
  imports: [
    SentryModule.forRootAsync({
      useFactory: async (configService: ConfigurationService) => ({
        dsn: configService.get('SENTRY_DSN'),
        debug: configService.get('SENTRY_DEBUG') == 'true',
        environment: configService.get('SENTRY_ENVIRONMENT'),
        //release: 'some_release', | null, // must create a release in sentry.io dashboard
        logLevel: LogLevel.Debug //based on sentry.io loglevel //
      }),
      inject: [ConfigurationService],
    }),
    ...
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

When I look at my Sentry dashboard, I only see some info/warning message generated during app startup but none of the exceptions or JS Errors like `null.push(''test')` from my graphql resolver are captured.
![Screen Shot 2019-10-09 at 7 02 29 PM](https://user-images.githubusercontent.com/3688337/66526736-b1916c80-eac7-11e9-99d0-7ad66a1f6bd4.png)

JS Error:
```typescript
  @Mutation(returns => User)
  @UseInterceptors(PictureInterceptor)
  async login(@Args() loginArgs: LoginArgs): Promise<User> {
    const t = null;
    t.push('l'); // <- throws an error
    return this.authService.login(loginArgs)
  }
```

Throw an error:
```typescript
  @Mutation(returns => User)
  @UseInterceptors(PictureInterceptor)
  async login(@Args() loginArgs: LoginArgs): Promise<User> {
    throw new Error('Sentry test');
    return this.authService.login(loginArgs)
  }
```

Do you have any idea why? is It because i'm using GraphQL?

**Comment by ntegral** [comment]
I'll look into your issue.

This definitely works.. It allows you to send message to sentry.io based on your above example.
put the code inside a try/catch statement.. 
constructor(@InjectSentry() private readonly client: SentryService) {
    client.error('test message');
  }

**Comment by cesar3030** [comment]
it works as expected when I inject the sentryService into the resolver constructor and I call `client.error('test message');` but if I throw an Error, it does not work.

When I call `client.error('test message');` from the GraphQL resolver, The event is logged twice:
<img width="1433" alt="Screen Shot 2019-10-11 at 3 48 31 PM" src="https://user-images.githubusercontent.com/3688337/66681717-4d92b380-ec41-11e9-9938-5d9b21bdf01a.png">

To avoid the event to be logged twice I need to instantiate the Nest App like this:
```
const app = await NestFactory.create(AppModule, {
   logger: false,
});
```


It is GraphQL related because when I throw an Error from a REST Controller, it is sent to Sentry. Only one event is sent to sentry even if logger is not disabled.

When an exception is thrown from a controller, the strack trace is not sent to Sentry:
```javascript
@Get('/')
  public async get() {
    const t = null;
    t.push('t');
  }
```

Sentry:
<img width="804" alt="Screen Shot 2019-10-11 at 4 20 05 PM" src="https://user-images.githubusercontent.com/3688337/66682416-0efdf880-ec43-11e9-9c12-d984fabb64bd.png">

Tell me if you want me to create different issues 😄 

Thank you very much for your help.

I'm going to investigate why Error thrown in GraphQL resolver are not even captured my nest internal logger (nothing is printed to the console).

**Comment by cesar3030** [comment]
@ntegral any updates on this?

**Comment by cesar3030** [comment]
I created an issue in nestjs/graphql repo: [https://github.com/nestjs/graphql/issues/449](https://github.com/nestjs/graphql/issues/449)

**Comment by cesar3030** [comment]
Updating to the last `@nestjs/core` version (6.9.0) fixed the issue.

**Comment by ntegral** [comment]
Thanks for following up with me on this. I used jest to test the library and could not replicate the issue.  I’ll change the peer dependency to that version. The updated version with tests has been deployed to npm.

Sent from my iPhone

On Nov 9, 2019, at 11:49 AM, César Jeanroy <notifications@github.com> wrote:

﻿

Updating to the last @nestjs/core version (6.9.0) fixed the issue.

**Comment by cesar3030** [comment]
My pleasure, Thanks for your work!
